x <- c(21, 62, 10,53)
labels <- c("London","New York","Singapore","Mumbai")
piepercent<- round(100*x/sum(x), 1)
png(file = "city_percentage_legends.jpg")
pie(x, labels=piepercent, main="City pie chart",col=rainbow(length(x)))
dev.off()